### ISSUE TITLE
SKK用の辞書ファイルの追加

### ISSUE THREAD

**Issue by pklion** [Umichang/nijisanji-ime-dic#5]
README.md の [THE IDOLM@STER IMEユーザー辞書登録用テキスト](https://ime.imas-db.jp/) にもあるような、SKK用の辞書ファイルがあると有難いです。

**Comment by Umichang** [comment]
SKK対応自体はおそらく可能です（登録フォーマットを見てからになりますが）。
ただ、手元にすぐ動作確認する環境がないので、どなたかがforkしていただく方が無難かなと考えています。
いずれにせよ手元にある変換用スクリプトでは対応していないので、そこからですね…。
